export const fData = [
    {
        name: "Outdoor",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBs1MkdXJIAR0wWchWPwu0u2X45xScC5DRPwFNHF8EjeFu5EBi",
        price: 2500000,
        mainName: "Modern 3-Bedroom Condo in SoMa",
        bed: 3,
        bath: 2,
        sqft: 2000,
        type: "House",
        yearBuilt: 2010,
        amenitites: ["Garden", "Swimming Pool", "Garage", "Gym"],
        location: "New York",
        id: 1
    },
    {
        name: "Living Room",
        mainName: "Modern 4-Bedroom Condo in SoMa",
        imageUrl: "https://media.designcafe.com/wp-content/uploads/2020/02/21010329/modern-living-room-design-ideas-768x512.jpg",
        price: 2000000,
        bed: 4,
        bath: 2,
        sqft: 1500,
        type: "Apartment",
        yearBuilt: 2010,
        amenitites: ["Garden", "Swimming Pool", "Garage", "Gym"],
        location: "New York",
        id: 2
    },
    {
        name: "Bedroom",
        mainName: "Modern 3-Bedroom Condo in SoMa",
        imageUrl: "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTA4L3Jhd3BpeGVsb2ZmaWNlOF9waG90b2dyYXBoeV9vZl9zY2FuZGluYXZpYW5fc3R5bGVfY296eV9tb2Rlcm5fYl9kYmM1NDA2Yy0zZTA0LTQzNzMtYWVhYi1iNjhkOTVkZjc5MTJfMS5qcGc.jpg",
        price: 1500000,
        bed: 3,
        bath: 1,
        sqft: 1000,
        type: "Apartment",
        yearBuilt: 2010,
        amenitites: ["Garden", "Swimming Pool", "Garage", "Gym"],
        location: "New York",
        id: 3
    },
    {
        name: "Dining Room",
        mainName: "Modern 6-Bedroom Mansion in SoMa",
        imageUrl: "https://www.decorilla.com/online-decorating/wp-content/uploads/2021/10/modern-farmhouse-dining-room-ideas-.jpeg",
        price: 4500000,
        bed: 6,
        bath: 3,
        sqft: 4800,
        type: "Apartment",
        yearBuilt: 2010,
        amenitites: ["Garden", "Swimming Pool", "Garage", "Gym"],
        location: "New York",
        id: 4
    },
    {
        name: "Office",
        mainName: "Modern 4-Bedroom Condo in SoMa",
        imageUrl: "https://img.freepik.com/free-photo/empty-room-with-chairs-desks_23-2149008873.jpg?size=626&ext=jpg&ga=GA1.1.1395880969.1709337600&semt=ais",
        price: 2550000,
        bed: 4,
        bath: 2,
        sqft: 1500,
        type: "Apartment",
        yearBuilt: 2010,
        amenitites: ["Garden", "Swimming Pool", "Garage", "Gym"],
        location: "New York",
        id: 5
    },
    {
        name: "Kids",
        mainName: "Modern 2-Bedroom Condo in SoMa",
        imageUrl: "https://media.designcafe.com/wp-content/uploads/2023/10/12175925/bunk-bed-with-desk.jpg",
        price: 1500000,
        bed: 2,
        bath: 1,
        sqft: 500,
        type: "Apartment",
        yearBuilt: 2010,
        amenitites: ["Garden", "Swimming Pool", "Garage", "Gym"],
        location: "New York",
        id: 6
    }
]